version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.7.0
    - 3.9.0
  - dependency-name: gatsby-plugin-nprogress
    versions:
    - 2.7.0
    - 2.9.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.7.1
    - 3.9.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
    - 2.8.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.11.0
    - 2.9.1
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.9.0
  - dependency-name: gatsby-plugin-webpack-bundle-analyser-v2
    versions:
    - 1.1.18
  - dependency-name: bl
    versions:
    - 4.0.3
